bundle_path "vendor/bundler_gems"
gem "rails", "2.3.5"
gem "haml"
gem 'mislav-will_paginate', '2.2.3'
gem "pdf-writer", "1.1.2"
gem "faker", "0.3.1"
gem "BlueCloth", "1.0.1"
gem "sqlite3-ruby", "1.2.5"
gem "factory_girl", "1.2.3"
gem "mocha", "0.9.8"
